# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8090

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-2zeu8v331a89513d3po.mysql.rds.aliyuncs.com:3306/db_decorate_1086?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: dbuserb
        password: fmd2018A
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    config-location: classpath:mybatis.xml

